DROP PROCEDURE IF EXISTS patch_Exam;
DELIMITER //
CREATE PROCEDURE patch_Exam()
  BEGIN

    SET @test = (
      SELECT COUNT(*)
      FROM information_schema.TABLE_CONSTRAINTS
      WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = "Exam");

    IF @test THEN
      SELECT "Modifying Exam table referential actions" AS "";

      SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
      SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

      ALTER TABLE Exam DROP FOREIGN KEY fkExamInterviewId;

      ALTER TABLE Exam ADD CONSTRAINT fkExamInterviewId
        FOREIGN KEY (InterviewId) REFERENCES Interview (Id)
        ON DELETE NO ACTION ON UPDATE CASCADE;

      ALTER TABLE Exam DROP FOREIGN KEY fkExamScanTypeId;

      ALTER TABLE Exam ADD CONSTRAINT fkExamScanTypeId
        FOREIGN KEY (ScanTypeId) REFERENCES ScanType (Id)
        ON DELETE NO ACTION ON UPDATE CASCADE;

      SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
      SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
    END IF;

  END //
DELIMITER ;

CALL patch_Exam();
DROP PROCEDURE IF EXISTS patch_Exam;
