-- MySQL Script generated by MySQL Workbench
-- Tue 27 Jun 2017 10:35:28 AM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Alder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Alder` ;

-- -----------------------------------------------------
-- Schema Alder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alder` DEFAULT CHARACTER SET latin1 ;
USE `Alder` ;

-- -----------------------------------------------------
-- Table `Alder`.`Wave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Wave` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Wave` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `Rank` INT UNSIGNED NOT NULL COMMENT '',
  `MetaDataSource` VARCHAR(45) NOT NULL COMMENT '',
  `ImageDataSource` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqName` (`Name` ASC)  COMMENT '',
  UNIQUE INDEX `uqRank` (`Rank` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Site` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Site` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `Alias` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Interview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Interview` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Interview` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `WaveId` INT UNSIGNED NOT NULL COMMENT '',
  `SiteId` INT UNSIGNED NOT NULL COMMENT '',
  `UId` VARCHAR(45) NOT NULL COMMENT '',
  `VisitDate` DATE NOT NULL COMMENT '',
  `Barcode` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqUIdWaveId` (`UId` ASC, `WaveId` ASC)  COMMENT '',
  INDEX `fkWaveId` (`WaveId` ASC)  COMMENT '',
  INDEX `fkSiteId` (`SiteId` ASC)  COMMENT '',
  CONSTRAINT `fkInterviewWaveId`
    FOREIGN KEY (`WaveId`)
    REFERENCES `Alder`.`Wave` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkInterviewSiteId`
    FOREIGN KEY (`SiteId`)
    REFERENCES `Alder`.`Site` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Modality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Modality` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Modality` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `Help` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqName` (`Name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`ScanType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`ScanType` ;

CREATE TABLE IF NOT EXISTS `Alder`.`ScanType` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `ModalityId` INT UNSIGNED NOT NULL COMMENT '',
  `WaveId` INT UNSIGNED NOT NULL COMMENT '',
  `Type` VARCHAR(255) NOT NULL COMMENT '',
  `SideCount` TINYINT NOT NULL DEFAULT 0 COMMENT '',
  `AcquisitionCount` TINYINT NOT NULL DEFAULT 1 COMMENT '',
  `ChildCount` TINYINT NOT NULL DEFAULT 0 COMMENT '',
  `AcquisitionNameFormat` VARCHAR(255) NOT NULL COMMENT '',
  `ChildNameFormat` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `FileSuffix` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fkModalityId` (`ModalityId` ASC)  COMMENT '',
  INDEX `fkWaveId` (`WaveId` ASC)  COMMENT '',
  INDEX `uqTypeModalityIdWaveId` (`Type` ASC, `ModalityId` ASC, `WaveId` ASC)  COMMENT '',
  CONSTRAINT `fkScanTypeModalityId`
    FOREIGN KEY (`ModalityId`)
    REFERENCES `Alder`.`Modality` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkScanTypeWaveId`
    FOREIGN KEY (`WaveId`)
    REFERENCES `Alder`.`Wave` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Exam` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Exam` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `InterviewId` INT UNSIGNED NOT NULL COMMENT '',
  `ScanTypeId` INT UNSIGNED NOT NULL COMMENT '',
  `Side` ENUM('right','left','none') NOT NULL DEFAULT 'none' COMMENT '',
  `Stage` VARCHAR(45) NOT NULL COMMENT '',
  `Interviewer` VARCHAR(45) NOT NULL COMMENT '',
  `DatetimeAcquired` DATETIME NULL COMMENT '',
  `Downloaded` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `SideIndex` TINYINT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `dkSide` (`Side` ASC)  COMMENT '',
  INDEX `fkInterviewId` (`InterviewId` ASC)  COMMENT '',
  UNIQUE INDEX `uqInterviewIdSideScanTypeId` (`InterviewId` ASC, `Side` ASC, `ScanTypeId` ASC)  COMMENT '',
  INDEX `fkScanTypeId` (`ScanTypeId` ASC)  COMMENT '',
  CONSTRAINT `fkExamInterviewId`
    FOREIGN KEY (`InterviewId`)
    REFERENCES `Alder`.`Interview` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkExamScanTypeId`
    FOREIGN KEY (`ScanTypeId`)
    REFERENCES `Alder`.`ScanType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Image` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Image` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `ExamId` INT UNSIGNED NOT NULL COMMENT '',
  `Acquisition` INT NOT NULL COMMENT '',
  `ParentImageId` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `Dimensionality` INT NOT NULL DEFAULT 2 COMMENT '',
  `Orphan` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fkImageExamId` (`ExamId` ASC)  COMMENT '',
  UNIQUE INDEX `uqExamIdAcquisition` (`ExamId` ASC, `Acquisition` ASC)  COMMENT '',
  INDEX `fkImageParentImageId` (`ParentImageId` ASC)  COMMENT '',
  CONSTRAINT `fkImageExamId`
    FOREIGN KEY (`ExamId`)
    REFERENCES `Alder`.`Exam` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkImageParentImageId`
    FOREIGN KEY (`ParentImageId`)
    REFERENCES `Alder`.`Image` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`User` ;

CREATE TABLE IF NOT EXISTS `Alder`.`User` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `Name` VARCHAR(255) NOT NULL COMMENT '',
  `Password` VARCHAR(255) NOT NULL COMMENT '',
  `Expert` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `InterviewId` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `LastLogin` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqName` (`Name` ASC)  COMMENT '',
  INDEX `dkLastLogin` (`LastLogin` ASC)  COMMENT '',
  INDEX `fkInterviewId` (`InterviewId` ASC)  COMMENT '',
  CONSTRAINT `fkUserInterviewId`
    FOREIGN KEY (`InterviewId`)
    REFERENCES `Alder`.`Interview` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Rating` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Rating` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `ImageId` INT UNSIGNED NOT NULL COMMENT '',
  `UserId` INT UNSIGNED NOT NULL COMMENT '',
  `Rating` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `DerivedRating` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fkImageId` (`ImageId` ASC)  COMMENT '',
  INDEX `fkUserId` (`UserId` ASC)  COMMENT '',
  INDEX `dkRating` (`Rating` ASC)  COMMENT '',
  UNIQUE INDEX `uqImageIdUserId` (`ImageId` ASC, `UserId` ASC)  COMMENT '',
  CONSTRAINT `fkRatingImageId`
    FOREIGN KEY (`ImageId`)
    REFERENCES `Alder`.`Image` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkRatingUserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Alder`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`UserHasModality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`UserHasModality` ;

CREATE TABLE IF NOT EXISTS `Alder`.`UserHasModality` (
  `UserId` INT UNSIGNED NOT NULL COMMENT '',
  `ModalityId` INT UNSIGNED NOT NULL COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`UserId`, `ModalityId`)  COMMENT '',
  INDEX `fkModalityId` (`ModalityId` ASC)  COMMENT '',
  INDEX `fkUserId` (`UserId` ASC)  COMMENT '',
  CONSTRAINT `fkUserHasModalityUserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Alder`.`User` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkUserHasModalityModalityId`
    FOREIGN KEY (`ModalityId`)
    REFERENCES `Alder`.`Modality` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`CodeGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`CodeGroup` ;

CREATE TABLE IF NOT EXISTS `Alder`.`CodeGroup` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `Value` INT NOT NULL DEFAULT 0 COMMENT '',
  `Name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqNameValue` (`Name` ASC, `Value` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`CodeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`CodeType` ;

CREATE TABLE IF NOT EXISTS `Alder`.`CodeType` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CodeGroupId` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `Code` VARCHAR(45) NOT NULL COMMENT '',
  `Value` INT NOT NULL DEFAULT 0 COMMENT '',
  `Active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  UNIQUE INDEX `uqCodeGroupIdCodeValue` (`CodeGroupId` ASC, `Code` ASC, `Value` ASC)  COMMENT '',
  INDEX `fkCodeGroupId` (`CodeGroupId` ASC)  COMMENT '',
  CONSTRAINT `fkCodeTypeCodeGroupId`
    FOREIGN KEY (`CodeGroupId`)
    REFERENCES `Alder`.`CodeGroup` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`Code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`Code` ;

CREATE TABLE IF NOT EXISTS `Alder`.`Code` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `ImageId` INT UNSIGNED NOT NULL COMMENT '',
  `UserId` INT UNSIGNED NOT NULL COMMENT '',
  `CodeTypeId` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fkImageId` (`ImageId` ASC)  COMMENT '',
  INDEX `fkUserId` (`UserId` ASC)  COMMENT '',
  UNIQUE INDEX `uqCodeTypeIdImageIdUserId` (`CodeTypeId` ASC, `ImageId` ASC, `UserId` ASC)  COMMENT '',
  INDEX `fkCodeTypeId` (`CodeTypeId` ASC)  COMMENT '',
  CONSTRAINT `fkCodeImageId`
    FOREIGN KEY (`ImageId`)
    REFERENCES `Alder`.`Image` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkCodeUserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Alder`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkCodeCodeTypeId`
    FOREIGN KEY (`CodeTypeId`)
    REFERENCES `Alder`.`CodeType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`ScanTypeHasCodeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`ScanTypeHasCodeType` ;

CREATE TABLE IF NOT EXISTS `Alder`.`ScanTypeHasCodeType` (
  `ScanTypeId` INT UNSIGNED NOT NULL COMMENT '',
  `CodeTypeId` INT UNSIGNED NOT NULL COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`ScanTypeId`, `CodeTypeId`)  COMMENT '',
  INDEX `fkCodeTypeId` (`CodeTypeId` ASC)  COMMENT '',
  INDEX `fkScanTypeId` (`ScanTypeId` ASC)  COMMENT '',
  CONSTRAINT `fkScanTypeHasCodeTypeScanTypeId`
    FOREIGN KEY (`ScanTypeId`)
    REFERENCES `Alder`.`ScanType` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkScanTypeHasCodeTypeCodeTypeId`
    FOREIGN KEY (`CodeTypeId`)
    REFERENCES `Alder`.`CodeType` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alder`.`ImageNote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alder`.`ImageNote` ;

CREATE TABLE IF NOT EXISTS `Alder`.`ImageNote` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `UpdateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `CreateTimestamp` TIMESTAMP NOT NULL COMMENT '',
  `ImageId` INT UNSIGNED NOT NULL COMMENT '',
  `UserId` INT UNSIGNED NOT NULL COMMENT '',
  `Note` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `fkUserId` (`UserId` ASC)  COMMENT '',
  INDEX `fkImageId` (`ImageId` ASC)  COMMENT '',
  CONSTRAINT `fkNoteUserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Alder`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fkNoteImageId`
    FOREIGN KEY (`ImageId`)
    REFERENCES `Alder`.`Image` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
